# Colors (Hyper)
# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xffffff'
[colors.cursor]
text = '0xF81CE5'
cursor = '0xffffff'
# Normal colors
[colors.normal]
black = '0x000000'
red = '0xfe0100'
green = '0x33ff00'
yellow = '0xfeff00'
blue = '0x0066ff'
magenta = '0xcc00ff'
cyan = '0x00ffff'
white = '0xd0d0d0'
# Bright colors
[colors.bright]
black = '0x808080'
red = '0xfe0100'
green = '0x33ff00'
yellow = '0xfeff00'
blue = '0x0066ff'
magenta = '0xcc00ff'
cyan = '0x00ffff'
white = '0xFFFFFF'

[window]
opacity = 0.8

[scrolling]
multiplier = 8

[font]
size = 10
[font.normal]
family = 'JetBrainsMonoNerdFont'
style = 'Regular'
[font.bold]
family = 'JetBrainsMonoNerdFont'
style = 'Bold'
[font.italic]
family = 'JetBrainsMonoNerdFont'
style = 'Light Italic'
